- C++/kruskals.cpp
The pushed code is about kruskals algorithm. Would be happy if the code gets merged.
> kruskals algorithm in cpp

- C++/baseConversion.cpp
Added a program in the Cpp folder that converts positive integers into different bases.
Done without strings or arrays as part of a challenge..
> Created  base conversion program in cpp

- C++/perfection.cpp
Added a perfection algorithm that determines the proper factors of a number and if it is abundant, deficient, or perfect.
Happy hacktoberfest!
> Created perfection.cpp

- Java/Anagram.java
- Java/LeftRotateArrayElement.java
- Java/RemoveDuplicate.java
- Java/RightRotate.java
- Java/SumRomColoumn.java
I have created Basic essential java programs for Repo.
These programs include:
1. Program to check Anagram or not
2. Program to Left and Right Rotate and Array elements
3. Program to sum row and column in a matrix
4. Program to remove duplicate elements in an array.
Could you merge this pull request?
Thank you.
> Created Essential Java Programs for Repo

- amstrongnumber.cpp
created a c++ program to detect 3 digit amstrong number
> amstrongnumber.cpp

- Python/blackjack.py
Added a simple blackjack program made in python to the python programs folder.
Also starred the repo
> Created Blackjack in Python

- C++/bubblesort.cpp
add bubble sort algorithm written in C++
> add bubble sort in c++

- palindrone.cpp
c++ program to detect a palindrone number
> palindrone.cpp

- C++/avlTree.cpp
> Added implementation of avl tree

- Java/Easter_Algorithm.java
Added an algorithm in java that determines the year Easter falls on every year after 1583.
Had to adapt this from my original JOptionPaneCode, as I didn't really feel like finding and adding in the Jar.
> Created Easter Determination Algorithm (Java)

- C++/linked_list.cpp
added the program of implementing a linked list in the CPP language. Please do let me know if any conflict or issue is there.
> linked list program by Amit giri ( Amitlpu-840 )

- C/Snake_Game.c
> Snake Game in C

- C++/SIEVE.cpp
> SIEVE OF ERATOSTHENES

- Java/quicksort.java
implemented Quicksort Algorithm on Java
> Added Quicksort in Java

- C/Linked List/Reversing Linked List using three sliding pointer method.c
Added a code in c to reverse linked list using three sliding pointers. Please review and merge it @abhilashmnair
>  Reversing Linked List using three sliding pointer method

- C++/GCD.CPP
Added GCD in C++ using recursive approach
> Added GCD in C++

- C++/BinaryTree_RightSideView.cpp
Solution to the problem to print right side view of a binary tree.
> Added BinaryTree_RightSideView.cpp

- Javascript/inspactor.js
this file help programmer to stop another user to stop inspect their website and protect from steel the functionality
> stop inspacting the website

- C++/Binary_tree_is_symmetirc_or_not.cpp
Solution to check whether a given binary tree is symmetric tree or not.
> Added Binary_tree_is_symmetirc_or_not.cpp

- C/Frequency_off_number.c
This code returns the appear frequency of numbers in an array, the code can be used to demonstrate how to work with an array in a function in c language.
> Frequency a numbers in array

- Python/fibonacci.py
This program takes user input as a length of fibonacci series and print the sequence till the given length.
> Create a fibonacci sequence using python

- Java/CircularLinkedList.java
- Java/trieInsertSearch.java
Insertion and Search using Trie
> Trie Insertion and search

- Java/Pattern.java
This programs takes user input as a number to get number of rows, after this a pattern of pyramid is printed using "*" and nested for loops.
The output of the programs is as shown below:
Enter number - 5
*     
* *    
* * *   
* * * *  
* * * * *
> Create a Pyramid Pattern using Java.

- C++/queue_pragya644.cpp
I added Queue code using Linked List.  It contain enqueue, dequeue and display function.
> Added Queue Code

- C#/SumOfNFibonacciNumbersDP.cs
Implemented sum of N Fibonacci numbers using dynamic programming in C#
> Sum of N Fibonacci numbers DP

- Java/DoublyLinkedList.java
program to create and traverse a Doubly Linked List
> DOUBLY LINKED LIST

- Java/CoinChangePermutation.java
- Java/PrintPermutations.java
Coin Change Permutations and String Permutations. If you found any conflicts do let me know.
> Coin Change Permutations and String Permutations

- Javascript/leetcodeprob.js
**Longest Substring Without Repeating Characters**
Approach:
1.We use the sliding window approach.
2.Here the while loop will start when the initial character has been deleted and the initial 
value has been incremented every time with -> begin = begin + 1.
This will increment it to 1 past the initial repeating character.
3. Time complexity: O(1)
4. Space complexity: O(n)
Fixes #(issue_no)
Replace `issue_no` in the above line, with the issue related to this PR.
```JavaScript
let s1 = "abcabcbb"
let s2 = "pwwkew"
var lengthOfLongestSubstring = function(s) {
let max = 0
let begin = 0
let set = new Set()
for(let end = 0; end < s.length;end++){
while(set.has(s[end])){
set.delete(s[begin])
begin = begin +1
}
set.add(s[end])
max = Math.max(max,end-begin+1)
}
return max
};
//Example 1
let …
```
> Leetcode Problem solved.

- Java/Maxofmin.java
- Java/RectArea.java
- Java/Stockspan.java
> Stock span Problem 

- C++/stackUsingTwoQueue.cpp
* Added this famous Question of DSA given in various sites
* *Time Complexity* of various Operation
Push : O(1)
Pop : O(n)
> Added Program to implement Stack using two queue

- C/Stack.c
This stack Program  is handle all operation like push, pop and Important for learning stack
> Created Stack Program in C

- Python/insertion_sort.py
> Added python code for Insertion sort

- Python/time.py
It creates a GET request to 'worldtimeapi.org'.
It parses the JSON string received and shows date and time in Kolkata, India
> This python code shows live time.

- C++/n_queen.cpp
> N Queen problem

- C++/ReverseNumber.cpp
reverse number is added with cpp program.
> Reverse Number is added

- Javascript/bottlesOfBeer.js
Here a a while loop for an old classic song that counts down from 99 bottles of beer to 1. Thanks enjoy.
> Added a while loop that counts down bottles of beer

- C++/insertion sort.cpp
Code for insertion sort in c++
> Create insertion sort.cpp

- C++/sum_of_all_subarray.cpp
Please merge, thank you
#Hacktoberfest2021
> Added sum_of_all_subarray.cpp

- Python/binary_search.py
added the code for the binary search in a list in the python language. Please do let me know if any conflict or issue is there.
> Added binary search in a list

- C++/all_soln_n_queen_BITMASKING-optiimized.cpp
- Using Bitmasking technique to efficiently evaluate the safe condition O(1) instead of O(N).
- USING BITMASK TECHNIQUE THE MOST OPTIMIZED SOLUTION TO FIND ALL DISTINCT SOLUTIONS TO NQUEENS PUZZLE
> all_soln_n_queen_BITMASKING-optiimized.cpp

- C/single_linklist_concatenation.c
The program is intended to do the following things
* Make two singly linked lists by performing various operations like insert at the start, at the end, at a particular position
* Finally it would concatenate  one LinkedList after another
* It is made in c language
> Added a program to concatenate of two singly linked list

- Java/MergeIntervals.java
> Added Important question in java

- C++/primeNumbers.cpp
Better Optimised. Hope you like it Sir.
> I m not using ctr variable and cmath in my code.

- Java/TowerofHanoi.java
> Added TowerofHanoi in Java

- C++/Transverse Matrix
How to find Transverse of a Matrix.
Hope you like it Sir.
> Tranverse Matrix.

- C++/Simple and Scientific Calculator
How to make Simple and Scientific Calculator using classes and functions.
Hope you like it Sir.
> Simple and Scientific Calculator.

- C++/Student_Class.cpp
How to make Student Class in C++
Hope you Like it Sir.
> Student_Class.cpp

- C++/Armstrong_no.cpp
How to find Armstrong Number.
Hope you Like it Sir.
> Armstrong_no.cpp

- C++/factorial.cpp
How to find Factorial of a number.
Hope you Like it Sir.
> factorial.cpp

- structure.cpp
Student Object using Structure.
Hope you Like it Sir.
> structure.cpp

- C/Calculator (Menu Driven) Program.c
Created a Calculator in C language using menu driven program.
> Calculator (Menu Driven) Program

- C++/Rock paper Scissors game
You can play rock paper scissors game through this code.
> Rock papaer scissors game

- Machine Learning/LinearRegression.ipynb
I have added simple beginner friendly code of Linear Regression algorithm of Machine Learning in Jupyter notebook.
> Added Linear Regression

- Python/discount.py
added the code for the calculating discount in the python language. Please do let me know if any conflict or issue is there.
> added code to calculate amount after discount

- C++/Quick_Sort
Added Quick Sort file in C++ Repository
> Quick_Sort 

- C++/Rotate_an_array.cpp
Added a program "rotate an array" in cpp
please review and merge.
thanks!
> Added rotate_an_array.cpp

- Python/BMI.py
added the code for body mass index in the python language. Please do let me know if any conflict or issue is there.
> added code for body mass index

- Javascript/Algorithm/Sort/binaryInsertionSort.js
We can use binary search to reduce the number of comparisons in normal insertion sort. Binary Insertion Sort uses binary search to find the proper location to insert the selected item at each iteration.
> add binary insertion sort function

- C++/BinaryTree_BFS_Traversal.cpp
Added a program for BFS traversal in Binary tree.
> Binary Tree BFS traversal
